version: '3.8'

services:
  redis-1:
    image: redis:latest
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    ports:
      - "6379:6379"
    networks:
      - redis-cluster-net

  redis-2:
    image: redis:latest
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    ports:
      - "6380:6379"
    networks:
      - redis-cluster-net

  redis-3:
    image: redis:latest
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    ports:
      - "6381:6379"
    networks:
      - redis-cluster-net

  redis-4:
    image: redis:latest
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    ports:
      - "6382:6379"
    networks:
      - redis-cluster-net

  redis-5:
    image: redis:latest
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    ports:
      - "6383:6379"
    networks:
      - redis-cluster-net

  redis-6:
    image: redis:latest
    command: redis-server --appendonly yes --cluster-enabled yes --cluster-config-file nodes.conf --cluster-node-timeout 5000 --port 6379
    ports:
      - "6384:6379"
    networks:
      - redis-cluster-net

networks:
  redis-cluster-net:
    driver: bridge
